# Generated by Django 3.1.6 on 2021-02-13 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='close_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='shop',
            name='open_time',
            field=models.TimeField(),
        ),
    ]
